=== ani-suri/ReWire/ReWire/HS/testarticles-v4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:c="customtypes.xsd" elementFormDefault="qualified" xml:lang="en">
	<xsd:import namespace="customtypes.xsd" schemaLocation="customtypes.xsd"/>
	<xsd:annotation>
		<xsd:documentation>
		Test Article Overview Information
		
		THE PROVIDER MAKES NO REPRESENTATIONS AND EXTENDS NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED. 
		THERE ARE NO EXPRESS OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
		
		Contact Information: ntpdb_support@niehs.nih.gov
		</xsd:documentation>
	</xsd:annotation>
	<xsd:element name="testArticles">
		<xsd:annotation>
			<xsd:documentation>
         		Highest level of XML data; individual test articles will be decendents.
         		attributes:
         			- dateCreated: the date this file was generated; will be updated quarterly.
         			- version: the version of this file; will be updated quarterly.
         		elements:
         			- comments: any comments with respect to this XML file
         			- url: address to the main NTP website
         			- contactInformation: contact email address to use for this XML file
         			- testArticle: individual test articles
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="comments" type="xsd:string"/>
				<xsd:element name="url" type="xsd:anyURI"/>
				<xsd:element name="contactInformation" type="xsd:string"/>
				<xsd:element ref="testArticle" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="dateCreated" type="c:dateTimeWithTimezone" use="required"/>
			<xsd:attribute name="version" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="testArticle">
		<xsd:annotation>
			<xsd:documentation>
         		Individual Test Article data.
         		attributes:
         			- casRN: The Chemical Abstract Services Registry Number for this Test Article
         			- ntpID: The NTP's internal identifier for this Test Article
         			- accID: The CEBS accession number
         		elements:
         			- primaryName: The Primary Name used to identify this Test Article
         			- synonyms: Any synonymous names that also refer to the same Test Article
         			- secondaryIDs: Any other forms of identifying this Test Article; id numbers or string names
         			- webUrl: web address to view the Test Article data page
         			- chemicalPropertiesURL: web address to view the Chemical Properties for this Test Article
         			- toxicityEffectsURL: web address to view the Toxicity Effects for this Test Article
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="primaryName" type="xsd:string"/>
				<xsd:element ref="synonyms"/>
				<xsd:element ref="secondaryIDs"/>			
				<xsd:element name="webURL" type="xsd:anyURI"/>
				<xsd:element name="chemicalPropertiesURL" type="xsd:anyURI" minOccurs="0"/>
				<xsd:element name="toxicityEffectsURL" type="xsd:anyURI" minOccurs="0"/>
				<xsd:element ref="studyAreas"/>
			</xsd:sequence>
			<xsd:attribute name="casRN" type="xsd:string" use="required"/>
			<xsd:attribute name="ntpID" type="xsd:string" use="required"/>
			<xsd:attribute name="accID" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="synonyms">
		<xsd:annotation>
			<xsd:documentation>
         		Potential list of synonyms for a given Test Article
         		elements:
         			- synonym: A synonymous name that refers to the same Test Article
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="synonym" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="secondaryIDs">
		<xsd:annotation>
			<xsd:documentation>
         		Potential list of secondary ids for a given Test Article
         		elements:
         			- secondaryID: Another identifier of this Test Article; can be a CASRN, other identifying number or string
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="secondaryID" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="studyAreas">
		<xsd:annotation>
			<xsd:documentation>
         		List of study areas for a given Test Article
         		elements:
         			- studyArea: A specific study area for this Test Article
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="studyArea" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="studyArea">
		<xsd:annotation>
			<xsd:documentation>
         		List of study areas for a given Test Article
         		attribute:
         			- type: The type of study area { }
         		elements:
         			- studies: The studies for this test article in this study area
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="studies" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="type" type="c:studyAreaType" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="studies">
		<xsd:annotation>
			<xsd:documentation>
         		List of studies for a given Test Article
         		elements:
         			- study: A specific study of this Test Article (can have multiples)
    		</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="study" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="study">
		<xsd:annotation>
			<xsd:documentation>
				A specific study for this test article
				attributes:
					- studyNumber: the study number used to identify the study
				elements:
					- publications: A list of publications for this study
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="publications" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="studyNumber" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="publications">
		<xsd:annotation>
			<xsd:documentation>
				A list of publications for this study
				elements:
					- publication: A specific of publication for this study
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="publication" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="publication">
		<xsd:annotation>
			<xsd:documentation>
				Any report information for this study
				attributes:
					- publicationNumber: the identifier for the publication
					- NTISNumber: if defined, the NTIS Number for the publication
					- NIHNumber: if defined, the NIH Number for the publication
				elements:
					- abstractURL: The web address for the abstract 	
					- url: The web address for the publication 	
					- citation: The citation for the publication 	
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="abstractURL" type="xsd:anyURI" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="url" type="xsd:anyURI" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="citation" type="xsd:string" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="publicationNumber" type="xsd:string" />
			<xsd:attribute name="NTISNumber" type="xsd:string" />
			<xsd:attribute name="NIHNumber" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>		
</xsd:schema>

=== ani-suri/ReWire/ReWire/HS/testarticles-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<testArticles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testarticles-v4.xsd" version="1" dateCreated="2018-10-24T19:40:41 GMT">
	<comments>THE PROVIDER MAKES NO REPRESENTATIONS AND EXTENDS NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED. THERE ARE NO EXPRESS OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</comments>
	<url>https://ntp.niehs.nih.gov</url>
	<contactInformation>ntpdb_support@niehs.nih.gov</contactInformation>
	<testArticle casRN="17924-92-4" ntpID="10770-C" accID="002-03013-0000-0000-9">
		<primaryName>Zearalenone</primaryName>
		<synonyms>
			<synonym>(S-(E))-3,4,5,6,9,10-Hexahydro-14,16-dihydroxy-3-methyl-1H-2-benzoxacyclotetradecin-1,7(8H)-dione</synonym>
		</synonyms>
		<secondaryIDs/>
		<webURL>https://tools.niehs.nih.gov/cebs3/ui/?casnumber=17924-92-4</webURL>
		<chemicalPropertiesURL>https://tools.niehs.nih.gov/cebs3/ntpviews/index.cfm?action=testarticle.properties&amp;cas_number=17924-92-4</chemicalPropertiesURL>
		<toxicityEffectsURL>https://tools.niehs.nih.gov/cebs3/ntpviews/index.cfm?action=testarticle.toxicity&amp;cas_number=17924-92-4</toxicityEffectsURL>
		<studyAreas>
			<studyArea type="Standard Toxicology and Carcinogenesis">
				<studies>
					<study studyNumber="C50226">
						<publications>
							<publication publicationNumber="TR-235" NTISNumber="PB83-165753" NIHNumber="83-1791">
								<abstractURL>https://ntp.niehs.nih.gov/go/tr235abs</abstractURL>
								<url>https://ntp.niehs.nih.gov/go/tr235</url>
								<citation>Carcinogenesis Bioassay of Zearalenone (CASRN 17924-92-4) in F344/N Rats and B6C3F1 Mice (Feed Study)</citation>
							</publication>
						</publications>
					</study>
				</studies>
			</studyArea>
			<studyArea type="Genetic Toxicology">
				<studies>
					<study studyNumber="577308">
						<publications>
							<publication publicationNumber="SA-2">
								<url>http://onlinelibrary.wiley.com/doi/10.1002/em.2860080702/pdf</url>
								<citation>Mortelmans, K., Haworth, S., Lawlor, T., Speck, W., Tainer, B., and Zeiger, E. Salmonella mutagenicity tests. II. Results from the testing of 270 chemicals Environ. Mutagen. Vol. 8 (Suppl 7) (1986) 1-119</citation>
							</publication>
						</publications>
					</study>
					<study studyNumber="669509">
						<publications>
							<publication publicationNumber="ML-8">
								<citation>McGregor, D., Brown, A., Cattanach, P., Edwards, I., McBride, D., Riach, C., and Caspary, W. Responses of the L5178Y tk+/tk- mouse lymphoma cell forward mutation assay: III. 72 coded chemicals. Environ. Molec. Mutagen. Vol. 12 (1988) 85-154</citation>
							</publication>
						</publications>
					</study>
					<study studyNumber="679562">
						<publications>
							<publication publicationNumber="CY-2">
								<citation>Galloway, S., Armstrong, M., Reuben, C., Colman, S., Brown, B., Cannon, C., Bloom, A., Nakamura, F., Ahmed, M., Duk, S., Rimpo, J., Margolin, B., Resnick, M., Anderson, B., and Zeiger, E. Chromosome aberration and sister chromatid exchanges in Chinese hamster ovary cells: Evaluations of 108 chemicals. Environ. Molec. Mutagen. Vol. 10 (Suppl 10) (1987) 1-176</citation>
							</publication>
						</publications>
					</study>
					<study studyNumber="853748">
						<publications>
							<publication publicationNumber="DL-11">
								<citation>Foureman, P., Mason, J.M., Valencia, R., Zimmering, S. Chemical Mutagenesis Testing in Drosophila. X. Results of 70 coded compounds tested for the National Toxicology Program. Environ. Molec. Mutagen. Vol. 23 (1994) 208-227</citation>
							</publication>
						</publications>
					</study>
				</studies>
			</studyArea>
		</studyAreas>
	</testArticle>
</testArticles>
